apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service-echo
  template:
    metadata:
      labels:
        app: web-service-echo
    spec:
      containers:
        - name: web-service-echo
          image: web-service-echo
          imagePullPolicy: Never
          ports:
            - containerPort: 8900
