apiVersion: v1
kind: Service
metadata:
  name: web-service-gin-svc
  labels:
    app: web-service-gin
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: web-service-gin
