apiVersion: v1
kind: Service
metadata:
  name: web-service-echo-svc
  labels:
    app: web-service-echo
spec:
  type: NodePort
  ports:
    - port: 8900
      nodePort: 30090
  selector:
    app: web-service-echo
